/** Nigeria states + FCT for tipster location coding. */
export const NIGERIA_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const EVENT_TYPES = [
  { value: "kidnap", label: "Kidnap / abduction" },
  { value: "robbery", label: "Robbery" },
  { value: "terrorism", label: "Terrorism" },
  { value: "protest", label: "Protest" },
  { value: "scam", label: "Scam" },
  { value: "battle", label: "Battle" },
  { value: "explosion", label: "Explosion" },
  { value: "other", label: "Other" },
] as const;

export const INCIDENT_STATUSES = [
  { value: "ongoing", label: "Ongoing" },
  { value: "in_negotiation", label: "In negotiation" },
  { value: "released", label: "Released" },
  { value: "rescued", label: "Rescued" },
  { value: "casualty_confirmed", label: "Casualty confirmed" },
  { value: "unresolved", label: "Unresolved" },
] as const;
